fix regex in commands and add new
copy commands from ccarh in order to fix regex

diff --git a/toolkit/sh/vox b/toolkit/sh/vox
--- a/toolkit/sh/vox
+++ b/toolkit/sh/vox
@@ -1,5 +1,5 @@
-###########################################################################
-# 						YDELTA
+#########################################################################
+# 						VOX
 # Programmed by: Tim Racinsky        Date: July, 1993
 # Copyright (c) 1993 David Huron
 #
@@ -9,47 +9,35 @@
 #
 #
 #	This shell program receives input from the command line and after 
-# checking it, passes it to the program ydelta.awk.
+# checking it, passes it to the program vox.awk.
 #
-INTERPRETATION=""
-REG_EXP=""
-HELP=""
 FILENAME=""
+HELP=""
 FLAG=""
-STNDIN=""
-USAGE1="USAGE: ydelta -h                   (Help Screen)"
-USAGE2="       ydelta [-s reg_exp] -i interpretation [file ...]"
-# 
-while getopts hi:s: arg
+STNDING=""
+USAGE1="USAGE: vox -h                 (Help Screen)"
+USAGE2="       vox [file ...]"
+#
+while getopts h arg
 do
 	case "$arg" in
-	s) 	REG_EXP="${OPTARG}";;
-	i) 	INTERPRETATION="${OPTARG}";;
 	h) 	HELP="ON";;
      [?]) echo "" 1>&2
 		echo "$USAGE1" 1>&2
 		echo "$USAGE2" 1>&2
-		exit;;
+		exit ;;
 	esac
 done
 shift `expr $OPTIND - 1`
 # If the help variable has been specified, print the help screen
 if [ -n "$HELP" ]
 then
-	if [ -f ${HUMDRUM}/bin/helpscrn/ydelta.hlp ]
+	if [ -f ${HUMDRUM}/bin/helpscrn/vox.hlp ]
 	then
-		cat ${HUMDRUM}/bin/helpscrn/ydelta.hlp
+		cat ${HUMDRUM}/bin/helpscrn/vox.hlp
 	else
 		echo "No help available on this command."
 	fi
-	exit
-fi
-if [ "X$INTERPRETATION" = X ]
-then
-	echo "ydelta: ERROR: Missing interpretation." 1>&2
-	echo "" 1>&2
-	echo "$USAGE1" 1>&2
-	echo "$USAGE2" 1>&2
 	exit
 fi
 # Process any remaining filenames
@@ -72,15 +60,14 @@ do
 		FILENAME="$FILENAME $1"
 		shift
 	else
-		echo "ydelta: ERROR: File not found: $1" 1>&2
+		echo "vox: ERROR: File not found: $1" 1>&2
 		FLAG="ON"
 		shift
 	fi
 done	
 # If only invalid files specified, exit
-if [ "X$FILENAME" = X -a -n "$FLAG" ]
+if [ -z "$FILENAME" -a -n "$FLAG" ]
 then
 	exit
 fi	
-# Invoke ydelta.awk with the specified options.
-$AWK_VER -f ${HUMDRUM}/bin/ydelta.awk  "DUMMY" "${REG_EXP:-null}" "$INTERPRETATION" $FILENAME
+$AWK_VER -f ${HUMDRUM}/bin/vox.awk "DUMMY" $FILENAME
